[book]
authors = ["poopsicles"]
language = "en"
multilingual = false
src = "src"
title = "Nebula: The Definitive Pygame Course"

[output.html]
curly-quotes = true
preferred-dark-theme = "coal"

[output.html.print]
enable = false